//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proekt_Studentski_Studentski_Domovi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soba()
        {
            this.Korisniks = new HashSet<Korisnik>();
            this.Smetkas = new HashSet<Smetka>();
        }
    
        public int Id_Soba { get; set; }
        public Nullable<int> Naziv_SD { get; set; }
        public Nullable<int> Sprat { get; set; }
        public Nullable<int> Broj_Soba { get; set; }
        public Nullable<int> Kapacitet { get; set; }
        public Nullable<int> Cena_Po_Lice { get; set; }
        public Nullable<bool> Dostapnost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smetka> Smetkas { get; set; }
        public virtual Studentski_Dom Studentski_Dom { get; set; }
    }
}
